---
-
  hosts: all

  tasks:
    - name: Print Hello
      debug:
        msg: "Hello there!"

    - name: Delete a file
      file:
        path: /etc/A.log
        state: absent
      become: yes
      become_method: sudo       

    - name: "Read a file content"
      shell: |
        cat /etc/host.conf
      register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"
