---
- hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
  - device_name: default_name

  tasks:
  - name: make interface down
    ios_interface:
      name: "{{ device_name }}"
      enabled: False
